### ISSUE TITLE
Unexpected overdraw when branching

### ISSUE THREAD

**Issue by JamesxX** [Robotechnic/alchemist#2]
https://github.com/Robotechnic/alchemist/blob/10071d9d6ed575fa49f3b8ec326d4db642789e35/src/drawer.typ#L521

I believe the linked line above causes overdraw when using branches. Example shown below (n.b., aliasing artefacts)

Current:
![image](https://github.com/user-attachments/assets/0b69c973-989d-4254-8d7f-b2620fbca9f6)

Without copying parent-ctx's links:
![image](https://github.com/user-attachments/assets/d48d3be7-4ac2-45ca-8a56-c16a377d76d4)

I think there's still some more overdraw happening but I haven't tracked it down yet.

Awesome package btw <3

**Comment by Robotechnic** [comment]
I was wondering where those aliasing artifacts come from. Thanks

**Comment by Robotechnic** [comment]
I found some other overdraw but it is now fixed. Thanks.
